/**
 * Named-tank encyclopedia for text → blueprint compose.
 *
 * Geometry is not stored here: each entry picks a visual `family` plus a handful
 * of identity knobs. Unknown prompts fall back to nation / era heuristics.
 *
 * Atlas originals stay in registry.js. `atlasId` means “this prompt should open
 * the already-authored drawing instead of emitting a second copy.”
 */

export const NATIONS = {
  us: { flag: '🇺🇸', country: 'UNITED STATES', countryCn: '美国', ink: 0xefcb9b, accent: 0xffa94d, sheet: '#12232c' },
  de: { flag: '🇩🇪', country: 'GERMANY', countryCn: '德国', ink: 0xb7d98e, accent: 0xe4ff6a, sheet: '#132518' },
  cn: { flag: '🇨🇳', country: 'CHINA', countryCn: '中国', ink: 0x9fe3c4, accent: 0xff6b6b, sheet: '#0c2420' },
  ru: { flag: '🇷🇺', country: 'RUSSIA', countryCn: '俄罗斯', ink: 0xc3deff, accent: 0x86b8ff, sheet: '#111d2e' },
  su: { flag: '🇷🇺', country: 'SOVIET UNION', countryCn: '苏联', ink: 0xb9d4f0, accent: 0xffc247, sheet: '#101924' },
  uk: { flag: '🇬🇧', country: 'UNITED KINGDOM', countryCn: '英国', ink: 0x8fd8ff, accent: 0xffc247, sheet: '#0d1f2e' },
  fr: { flag: '🇫🇷', country: 'FRANCE', countryCn: '法国', ink: 0xcbbbff, accent: 0xa78bfa, sheet: '#161c33' },
  il: { flag: '🇮🇱', country: 'ISRAEL', countryCn: '以色列', ink: 0xd4c48a, accent: 0xf0c400, sheet: '#1c1a12' },
  kr: { flag: '🇰🇷', country: 'SOUTH KOREA', countryCn: '韩国', ink: 0x8fe0d2, accent: 0xff6b6b, sheet: '#0e2422' },
  jp: { flag: '🇯🇵', country: 'JAPAN', countryCn: '日本', ink: 0xd8e4f0, accent: 0xff6b6b, sheet: '#141820' },
  it: { flag: '🇮🇹', country: 'ITALY', countryCn: '意大利', ink: 0xa8d4b0, accent: 0xffc247, sheet: '#122018' },
  in: { flag: '🇮🇳', country: 'INDIA', countryCn: '印度', ink: 0xf0c48a, accent: 0xff7a3d, sheet: '#1c1610' },
  se: { flag: '🇸🇪', country: 'SWEDEN', countryCn: '瑞典', ink: 0xa8d8ff, accent: 0xffc247, sheet: '#101820' },
  ua: { flag: '🇺🇦', country: 'UKRAINE', countryCn: '乌克兰', ink: 0xffe08a, accent: 0x5b8cff, sheet: '#16140e' },
  pl: { flag: '🇵🇱', country: 'POLAND', countryCn: '波兰', ink: 0xf0b8c0, accent: 0xff6b6b, sheet: '#1c1214' },
  tr: { flag: '🇹🇷', country: 'TURKEY', countryCn: '土耳其', ink: 0xe8b8b0, accent: 0xff6b6b, sheet: '#1a1212' },
};

export const COUNTRY_ALIASES = [
  { nation: 'us', keys: ['美国', '美利坚', 'unitedstates', 'usa', 'us', 'american', 'america'] },
  { nation: 'de', keys: ['德国', '德意志', 'germany', 'german', 'deutschland'] },
  { nation: 'cn', keys: ['中国', '中华', 'china', 'chinese', 'prc'] },
  { nation: 'ru', keys: ['俄罗斯', '俄国', 'russia', 'russian', 'россия'] },
  { nation: 'su', keys: ['苏联', 'soviet', 'ussr', 'ссср'] },
  { nation: 'uk', keys: ['英国', '英军', 'britain', 'british', 'uk', 'england', 'unitedkingdom'] },
  { nation: 'fr', keys: ['法国', '法兰西', 'france', 'french'] },
  { nation: 'il', keys: ['以色列', 'israel', 'israeli', 'idf'] },
  { nation: 'kr', keys: ['韩国', '南韩', 'korea', 'korean', 'rok'] },
  { nation: 'jp', keys: ['日本', 'japan', 'japanese'] },
  { nation: 'it', keys: ['意大利', 'italy', 'italian'] },
  { nation: 'in', keys: ['印度', 'india', 'indian'] },
  { nation: 'se', keys: ['瑞典', 'sweden', 'swedish'] },
  { nation: 'ua', keys: ['乌克兰', 'ukraine', 'ukrainian'] },
  { nation: 'pl', keys: ['波兰', 'poland', 'polish'] },
  { nation: 'tr', keys: ['土耳其', 'turkey', 'turkish'] },
];

/** First unused catalog id for a nation-only prompt (“美国坦克”). */
export const COUNTRY_QUEUE = {
  us: ['m60', 'm1a1', 'sherman'],
  de: ['leopard2a4', 'leopard1', 'panther'],
  cn: ['type96b', 'type15', 'type59'],
  ru: ['t72b3', 't14', 't80bvm'],
  su: ['t72b3', 't34', 't55'],
  uk: ['chieftain', 'centurion'],
  fr: ['amx30'],
  il: ['merkava4'],
  kr: ['k2'],
  jp: ['type10'],
  it: ['ariete'],
  in: ['arjun'],
  se: ['strv122'],
  ua: ['t84'],
  pl: ['pt91'],
  tr: ['altay'],
};

export const CATALOG = [
  {
    id: 'm1a2',
    atlasId: 'm1a2',
    aliases: ['m1a2', 'm1a2abrams', 'm1a2sepv3', '艾布拉姆斯', 'm1艾布拉姆斯', '艾布拉姆'],
    nation: 'us',
  },
  {
    id: 'leopard2a7',
    atlasId: 'leopard2a7',
    aliases: ['leopard2a7', 'leo2a7', '豹2a7', '豹二a7'],
    nation: 'de',
  },
  {
    id: 'ztz99a',
    atlasId: 'ztz99a',
    aliases: ['ztz99a', 'type99a', '99a', '99a式', '99式a', '九九a'],
    nation: 'cn',
  },
  {
    id: 't90m',
    atlasId: 't90m',
    aliases: ['t90m', 't90mproryv', 't90', '突破', 't90突破'],
    nation: 'ru',
  },
  {
    id: 'challenger2',
    atlasId: 'challenger2',
    aliases: ['challenger2', 'cr2', '挑战者2', '挑战者二'],
    nation: 'uk',
  },
  {
    id: 'leclerc',
    atlasId: 'leclerc',
    aliases: ['leclerc', 'leclercxlr', '勒克莱尔', '勒克勒克'],
    nation: 'fr',
  },
  {
    id: 'tiger1',
    atlasId: 'tiger1',
    aliases: ['tiger1', 'tigeri', 'pzvi', '虎1', '虎i', '虎式', '六号坦克'],
    nation: 'de',
  },

  entry('m1a1', {
    aliases: ['m1a1', 'm1a1abrams', 'm1a1ha', 'm1艾布拉姆斯早期', '早期艾布拉姆斯'],
    nation: 'us',
    family: 'abrams',
    prefix: 'M1A1',
    name: 'M1A1 ABRAMS',
    nameCn: 'M1A1「艾布拉姆斯」',
    designation: 'MBT · HA · 1985 →',
    mass: '61.3 t',
    crew: '4 · 车长 炮长 装填手 驾驶员',
    powerpack: 'HONEYWELL AGT-1500 GAS TURBINE · 1500 hp',
    armament: '120 mm M256 SMOOTHBORE L/44',
    armour: 'CHOBHAM + DEPLETED URANIUM MESH',
    envelope: '9.77 × 3.66 × 2.44 m',
    barrelLength: 4.05,
    wheelCount: 7,
    features: { gasTurbine: true, mesh: false, citv: false },
    structure: [
      ['Low angular special-armour turret', '低矮棱角复合装甲炮塔'],
      ['AGT-1500 gas turbine exhaust', 'AGT-1500 燃气轮机尾排'],
      ['120 mm M256 without TUSK cages', '无 TUSK 套件的 120 毫米 M256'],
    ],
  }),
  entry('m60', {
    aliases: ['m60', 'm60patton', 'm60a3', '巴顿', 'm60巴顿', '巴顿坦克'],
    nation: 'us',
    family: 'cast',
    prefix: 'M60',
    name: 'M60 PATTON',
    nameCn: 'M60「巴顿」',
    designation: 'MBT · M60A3 TTS · 1960 →',
    mass: '52 t',
    crew: '4 · commander gunner loader driver',
    powerpack: 'CONTINENTAL AVDS-1790 DIESEL · 750 hp',
    armament: '105 mm M68 RIFLED',
    armour: 'CAST HULL AND TURRET',
    envelope: '9.44 × 3.63 × 3.27 m',
    barrelLength: 5.15,
    wheelCount: 6,
    features: { diesel: true, bustle: true, tall: true },
    structure: [
      ['Cast hemispherical turret', '铸造半球形炮塔'],
      ['Needlenose 105 mm M68', '细长 105 毫米 M68 线膛炮'],
      ['Six large stamped road wheels', '六对大直径负重轮'],
    ],
  }),
  entry('sherman', {
    aliases: ['sherman', 'm4sherman', 'm4a3', 'm4', '谢尔曼', '雪曼'],
    nation: 'us',
    family: 'wwii',
    prefix: 'M4',
    name: 'M4 SHERMAN',
    nameCn: 'M4「谢尔曼」',
    designation: 'MEDIUM TANK · M4A3 (76) W',
    mass: '33 t',
    crew: '5 · commander gunner loader driver assistant',
    powerpack: 'FORD GAA V8 · 450 hp',
    armament: '76 mm M1 GUN',
    armour: 'ROLLED / CAST HULL, 63 mm GLACIS',
    envelope: '7.54 × 2.67 × 2.97 m',
    barrelLength: 3.9,
    wheelCount: 6,
    features: { wwii: true, frontDrive: true, muzzleBrake: true, diesel: true },
    structure: [
      ['Front drive sprockets', '前置主动轮'],
      ['VVSS/HVSS bogie pairs', '成对负重轮转向架'],
      ['Cast turret with 76 mm gun', '铸造炮塔与 76 毫米炮'],
    ],
  }),

  entry('leopard2a4', {
    aliases: ['leopard2a4', 'leo2a4', '豹2a4', '豹二a4', '早期豹2'],
    nation: 'de',
    family: 'leopard',
    prefix: 'LEO2A4',
    name: 'LEOPARD 2A4',
    nameCn: '豹 2A4',
    designation: 'MBT · KAMPFPANZER · 1985 →',
    mass: '55.2 t',
    crew: '4 · Kommandant Richtschütze Ladeschütze Fahrer',
    powerpack: 'MTU MB 873 Ka-501 DIESEL · 1500 PS',
    armament: 'RHEINMETALL Rh-120 SMOOTHBORE L/44',
    armour: 'SPACED / COMPOSITE, VERTICAL TURRET FACE',
    envelope: '9.67 × 3.70 × 2.79 m',
    barrelLength: 4.4,
    wheelCount: 7,
    features: { diesel: true, wedge: false, peri: true },
    structure: [
      ['Vertical welded turret face', '垂直焊接炮塔正面'],
      ['Rh-120 L/44 without wedge kit', '无楔形附加装甲的 L/44'],
      ['Seven road wheels, rear drive', '七对负重轮、后置主动轮'],
    ],
  }),
  entry('leopard1', {
    aliases: ['leopard1', 'leo1', '豹1', '豹一'],
    nation: 'de',
    family: 'cast',
    prefix: 'LEO1',
    name: 'LEOPARD 1',
    nameCn: '豹 1',
    designation: 'MBT · KAMPFPANZER 1 A5',
    mass: '42.5 t',
    crew: '4',
    powerpack: 'MTU MB 838 CaM-500 · 830 PS',
    armament: 'L7A3 105 mm RIFLED',
    armour: 'LIGHT CAST / WELDED — MOBILITY FIRST',
    envelope: '9.54 × 3.37 × 2.76 m',
    barrelLength: 5.15,
    wheelCount: 7,
    features: { diesel: true, peri: true },
    structure: [
      ['Rounded cast turret', '浑圆铸造炮塔'],
      ['Light armour, high power-to-weight', '轻装甲、高功重比'],
      ['L7 105 mm NATO gun', 'L7 105 毫米北约炮'],
    ],
  }),
  entry('panther', {
    aliases: ['panther', 'panthertank', 'pzv', '豹式', '五号坦克', 'panzer5'],
    nation: 'de',
    family: 'slope',
    prefix: 'PZV',
    name: 'PANTHER AUSF. G',
    nameCn: '豹式 G 型',
    designation: 'MEDIUM TANK · PZ.KPFW. V',
    mass: '44.8 t',
    crew: '5',
    powerpack: 'MAYBACH HL 230 P30 · 700 PS',
    armament: '7.5 cm KwK 42 L/70',
    armour: '80 mm GLACIS AT 55°',
    envelope: '8.66 × 3.42 × 2.99 m',
    barrelLength: 5.17,
    wheelCount: 8,
    features: { wwii: true, muzzleBrake: true, diesel: true, interleaved: true },
    structure: [
      ['Long 55° glacis plate', '55° 长首上装甲板'],
      ['KwK 42 L/70 with muzzle brake', '带炮口制退器的 L/70'],
      ['Interleaved road wheels', '交错式负重轮'],
    ],
  }),
  entry('kingtiger', {
    aliases: ['kingtiger', 'tigera', 'tigera2', 'tigerii', 'konigstiger', '虎王', '虎ii', '国王虎'],
    nation: 'de',
    family: 'wwii',
    prefix: 'TG2',
    name: 'TIGER II',
    nameCn: '虎王',
    designation: 'HEAVY TANK · PZ.KPFW. VI AUSF. B',
    mass: '69.8 t',
    crew: '5',
    powerpack: 'MAYBACH HL 230 P30 · 700 PS',
    armament: '8.8 cm KwK 43 L/71',
    armour: '150 mm SLOPED GLACIS',
    envelope: '10.29 × 3.76 × 3.09 m',
    barrelLength: 6.3,
    wheelCount: 9,
    features: { wwii: true, muzzleBrake: true, diesel: true, slopedNose: true },
    structure: [
      ['Porsche turret / Henschel hull', '保时捷炮塔与亨舍尔车体'],
      ['Very long 88 mm L/71', '极长的 88 毫米 L/71'],
      ['Sloped 150 mm glacis', '倾斜 150 毫米首上装甲'],
    ],
  }),

  entry('type96b', {
    aliases: ['type96', 'type96b', 'ztz96b', '96式', '96b', '九六'],
    nation: 'cn',
    family: 'chinese',
    prefix: 'ZTZ96',
    name: 'ZTZ-96B',
    nameCn: '96B 式主战坦克',
    designation: 'MBT · TYPE 96B',
    mass: '42.5 t',
    crew: '3 · 车长 炮长 驾驶员（自动装弹）',
    powerpack: '150HB IMPROVED DIESEL · 1000 hp',
    armament: '125 mm SMOOTHBORE + CAROUSEL',
    armour: 'WELDED HULL + FY-SERIES ERA',
    envelope: '10.28 × 3.30 × 2.30 m',
    barrelLength: 5.7,
    wheelCount: 6,
    features: { carousel: true, era: true, diesel: true, laser: false },
    structure: [
      ['FY reactive bricks on the turret', '炮塔 FY 反应装甲块'],
      ['Carousel autoloader, three crew', '转盘自动装弹、三人乘员'],
      ['Six road wheels, compact hull', '六对负重轮、紧凑车体'],
    ],
  }),
  entry('type15', {
    aliases: ['type15', 'ztz15', '15式', '十五式', '轻坦15'],
    nation: 'cn',
    family: 'light',
    prefix: 'ZTZ15',
    name: 'ZTZ-15',
    nameCn: '15 式轻型坦克',
    designation: 'LIGHT TANK · TYPE 15',
    mass: '33 t',
    crew: '3',
    powerpack: 'ELECTRONICALLY CONTROLLED DIESEL · 1000 hp',
    armament: '105 mm RIFLED + AUTOLOADER',
    armour: 'MODULAR COMPOSITE + ERA OPTION',
    envelope: '9.20 × 3.30 × 2.50 m',
    barrelLength: 5.1,
    wheelCount: 6,
    features: { bustleAuto: true, diesel: true, hydrogas: true, peri: true },
    structure: [
      ['Compact highland light tank', '高原轻型坦克轮廓'],
      ['105 mm autoloading gun', '105 毫米自动装填火炮'],
      ['Hydro-pneumatic suspension', '油气弹簧悬挂'],
    ],
  }),
  entry('type59', {
    aliases: ['type59', 'ztz59', '59式', '五九式'],
    nation: 'cn',
    family: 'slope',
    prefix: 'ZTZ59',
    name: 'TYPE 59',
    nameCn: '59 式中型坦克',
    designation: 'MEDIUM TANK · TYPE 59',
    mass: '36 t',
    crew: '4',
    powerpack: '12150L DIESEL · 520 hp',
    armament: '100 mm RIFLED',
    armour: 'CAST TURRET, SLOPED HULL',
    envelope: '9.00 × 3.27 × 2.59 m',
    barrelLength: 5.0,
    wheelCount: 5,
    features: { diesel: true, bustle: false },
    structure: [
      ['T-54 lineage sloped hull', 'T-54 谱系倾斜车体'],
      ['Cast dome turret', '铸造穹顶炮塔'],
      ['Five large Christie-style wheels', '五对大直径负重轮'],
    ],
  }),

  entry('t72b3', {
    aliases: ['t72', 't72b3', 't72b', 't-72', 't72b3m'],
    nation: 'ru',
    family: 'soviet',
    prefix: 'T72',
    name: 'T-72B3',
    nameCn: 'T-72B3',
    designation: 'MBT · OBJ. 184-M3',
    mass: '46.5 t',
    crew: '3 · командир наводчик механик-водитель',
    powerpack: 'V-92S2F DIESEL · 1130 hp',
    armament: '2A46M-5 125 mm + CAROUSEL',
    armour: 'KONTAKT-5 / RELIKT ERA',
    envelope: '9.53 × 3.46 × 2.23 m',
    barrelLength: 4.8,
    wheelCount: 6,
    features: { carousel: true, era: true, diesel: true, slat: true },
    structure: [
      ['Low dome turret with ERA', '低矮穹顶炮塔加反应装甲'],
      ['Floor carousel autoloader', '底板转盘自动装弹机'],
      ['Six road wheels, compact hull', '六对负重轮、短车体'],
    ],
  }),
  entry('t80bvm', {
    aliases: ['t80', 't80bvm', 't80u', 't80bv', 't-80'],
    nation: 'ru',
    family: 'soviet',
    prefix: 'T80',
    name: 'T-80BVM',
    nameCn: 'T-80BVM',
    designation: 'MBT · OBJ. 219M',
    mass: '46 t',
    crew: '3',
    powerpack: 'GTD-1250 GAS TURBINE · 1250 hp',
    armament: '2A46M-1 125 mm + CAROUSEL',
    armour: 'RELIKT ERA + SOFT-KILL APS',
    envelope: '9.66 × 3.58 × 2.22 m',
    barrelLength: 4.8,
    wheelCount: 6,
    features: { carousel: true, era: true, gasTurbine: true, slat: true },
    structure: [
      ['Gas-turbine T-80 silhouette', '燃汽轮机 T-80 轮廓'],
      ['Relikt bricks and slat cages', '「化石」砖与格栅装甲'],
      ['Six rubber-tyred road wheels', '六对橡胶负重轮'],
    ],
  }),
  entry('t14', {
    aliases: ['t14', 't14armata', 'armata', 't-14', '阿玛塔', '阿尔玛塔', 't14阿玛塔'],
    nation: 'ru',
    family: 'armata',
    prefix: 'T14',
    name: 'T-14 ARMATA',
    nameCn: 'T-14「阿玛塔」',
    designation: 'MBT · OBJ. 148',
    mass: '55 t',
    crew: '3 · 全员在车体前部乘员舱',
    powerpack: '12N360 DIESEL · 1500 hp',
    armament: '2A82-1M 125 mm UNMANNED TURRET',
    armour: 'AFGHANIT APS + MALACHIT ERA',
    envelope: '10.80 × 3.50 × 3.30 m',
    barrelLength: 5.6,
    wheelCount: 7,
    features: { unmanned: true, era: true, diesel: true, peri: true, bustleAuto: true },
    structure: [
      ['Unmanned turret, crew in hull capsule', '无人炮塔，乘员在车体舱'],
      ['Seven road wheels on a long hull', '七对负重轮、加长车体'],
      ['Afghanit APS launch tubes', '「阿富汗石」主动防护发射管'],
    ],
  }),
  entry('t34', {
    aliases: ['t34', 't34/85', 't3485', 't-34', 't34坦克'],
    nation: 'su',
    family: 'slope',
    prefix: 'T34',
    name: 'T-34-85',
    nameCn: 'T-34-85',
    designation: 'MEDIUM TANK · 1944',
    mass: '32 t',
    crew: '5',
    powerpack: 'V-2-34 DIESEL · 500 hp',
    armament: '85 mm ZIS-S-53',
    armour: '45 mm GLACIS AT 60°',
    envelope: '8.10 × 3.00 × 2.72 m',
    barrelLength: 4.0,
    wheelCount: 5,
    features: { wwii: true, diesel: true, christie: true },
    structure: [
      ['60° glacis, Christie suspension', '60° 首上装甲与克里斯蒂悬挂'],
      ['Hexagonal 85 mm turret', '六角形 85 毫米炮塔'],
      ['Five large road wheels, no rollers', '五对大轮、无托带轮'],
    ],
  }),
  entry('t55', {
    aliases: ['t55', 't-55', 't54', 't-54'],
    nation: 'su',
    family: 'slope',
    prefix: 'T55',
    name: 'T-55',
    nameCn: 'T-55',
    designation: 'MBT · OBJ. 155',
    mass: '36 t',
    crew: '4',
    powerpack: 'V-55 DIESEL · 580 hp',
    armament: '100 mm D-10T2S',
    armour: 'CAST DOME TURRET',
    envelope: '9.00 × 3.27 × 2.40 m',
    barrelLength: 5.35,
    wheelCount: 5,
    features: { diesel: true },
    structure: [
      ['Classic Soviet dome turret', '经典苏系穹顶炮塔'],
      ['Five road wheels, rear sprocket', '五对负重轮、后置主动轮'],
      ['100 mm rifled D-10', '100 毫米 D-10 线膛炮'],
    ],
  }),

  entry('chieftain', {
    aliases: ['chieftain', 'fv4201', '酋长', '酋长坦克'],
    nation: 'uk',
    family: 'challenger',
    prefix: 'CHFT',
    name: 'CHIEFTAIN',
    nameCn: '酋长',
    designation: 'MBT · FV4201 Mk 10',
    mass: '55 t',
    crew: '4',
    powerpack: 'LEYLAND L60 MULTIFUEL · 750 hp',
    armament: 'L11A5 120 mm RIFLED',
    armour: 'CAST / WELDED, VERY SLOPED GLACIS',
    envelope: '10.80 × 3.50 × 2.90 m',
    barrelLength: 5.5,
    wheelCount: 6,
    features: { thermalSleeve: true, diesel: true, reclinedDriver: true },
    structure: [
      ['Extremely sloped driver glacis', '极倾斜的驾驶员首上装甲'],
      ['120 mm L11 rifled gun', '120 毫米 L11 线膛炮'],
      ['Reclined driver under the glacis', '半躺在首下的驾驶员'],
    ],
  }),
  entry('centurion', {
    aliases: ['centurion', 'fv4007', '百夫长', '百人队长'],
    nation: 'uk',
    family: 'cast',
    prefix: 'CENT',
    name: 'CENTURION Mk 5',
    nameCn: '百夫长 Mk 5',
    designation: 'MBT · FV4007',
    mass: '51 t',
    crew: '4',
    powerpack: 'ROLLS-ROYCE METEOR · 650 hp',
    armament: 'L7 105 mm RIFLED',
    armour: 'CAST TURRET, 76 mm GLACIS',
    envelope: '9.85 × 3.39 × 3.01 m',
    barrelLength: 5.15,
    wheelCount: 6,
    features: { diesel: true, bustle: true },
    structure: [
      ['High cast turret with stowage bins', '高铸造炮塔与侧箱'],
      ['L7 105 mm — NATO standard', 'L7 105 毫米北约制式炮'],
      ['Six road wheels, rear drive', '六对负重轮'],
    ],
  }),

  entry('amx30', {
    aliases: ['amx30', 'amx-30', 'amx30b2'],
    nation: 'fr',
    family: 'cast',
    prefix: 'AMX30',
    name: 'AMX-30 B2',
    nameCn: 'AMX-30 B2',
    designation: 'MBT · CHAR DE BATAILLE',
    mass: '36 t',
    crew: '4',
    powerpack: 'HISPANO-SUIZA HS-110 · 720 hp',
    armament: 'CN-105-F1 105 mm',
    armour: 'LIGHT CAST — MOBILITY SCHOOL',
    envelope: '9.48 × 3.10 × 2.86 m',
    barrelLength: 5.6,
    wheelCount: 5,
    features: { diesel: true, peri: true },
    structure: [
      ['Small cast turret, five wheels', '小铸造炮塔、五对负重轮'],
      ['Oscillating-era French mobility', '法国机动优先学派'],
      ['105 mm CN-105-F1', '105 毫米 CN-105-F1'],
    ],
  }),

  entry('merkava4', {
    aliases: ['merkava', 'merkava4', 'merkavaiv', 'merkava4m', '梅卡瓦', '梅卡瓦4', '战车4'],
    nation: 'il',
    family: 'merkava',
    prefix: 'MK4',
    name: 'MERKAVA Mk 4',
    nameCn: '梅卡瓦 Mk 4',
    designation: 'MBT · MERKAVA 4M BARAK',
    mass: '65 t',
    crew: '4 · 可载步兵从尾门出入',
    powerpack: 'GENERAL DYNAMICS GD883 DIESEL · 1500 hp',
    armament: '120 mm MG253 SMOOTHBORE',
    armour: 'MODULAR COMPOSITE + TROPHY APS',
    envelope: '9.04 × 3.72 × 2.66 m',
    barrelLength: 4.4,
    wheelCount: 6,
    features: { diesel: true, frontEngine: true, rearDoor: true, trophy: true, bustle: true },
    structure: [
      ['Front-mounted powerpack', '前置动力舱'],
      ['Rear infantry clamshell door', '尾部步兵舱门'],
      ['Trophy APS launchers on the turret', '炮塔「战利品」主动防护'],
    ],
  }),

  entry('k2', {
    aliases: ['k2', 'k2blackpanther', 'blackpanther', '黑豹', 'k2黑豹', '韩国黑豹'],
    nation: 'kr',
    family: 'leopard',
    prefix: 'K2',
    name: 'K2 BLACK PANTHER',
    nameCn: 'K2「黑豹」',
    designation: 'MBT · K2',
    mass: '55 t',
    crew: '3 · 尾舱自动装弹',
    powerpack: 'MTU MB-883 DIESEL · 1500 hp',
    armament: 'CN08 120 mm L/55 + BUSTLE AUTOLOADER',
    armour: 'K2 COMPOSITE + ERA OPTION',
    envelope: '10.80 × 3.60 × 2.40 m',
    barrelLength: 5.33,
    wheelCount: 6,
    features: { diesel: true, peri: true, hydrogas: true, bustleAuto: true, wedge: true },
    structure: [
      ['Wedge turret with bustle autoloader', '楔形炮塔与尾舱自动装弹'],
      ['Hydro-pneumatic suspension', '油气弹簧悬挂'],
      ['L/55 120 mm CN08', '120 毫米 CN08 L/55'],
    ],
  }),

  entry('type10', {
    aliases: ['type10', '10式', '十式', 'tkx'],
    nation: 'jp',
    family: 'leclerc',
    prefix: 'TK10',
    name: 'TYPE 10',
    nameCn: '10 式主战坦克',
    designation: 'MBT · TYPE 10',
    mass: '44 t',
    crew: '3',
    powerpack: '8VG DIESEL · 1200 hp',
    armament: '120 mm L/44 + AUTOLOADER',
    armour: 'MODULAR NANO-CRYSTALLINE STEEL',
    envelope: '9.42 × 3.24 × 2.30 m',
    barrelLength: 4.4,
    wheelCount: 5,
    features: { diesel: true, peri: true, hydrogas: true, bustleAuto: true },
    structure: [
      ['Compact modular Japanese MBT', '紧凑模块化日本主战坦克'],
      ['Five road wheels, hydrogas units', '五对负重轮与油气悬挂'],
      ['Bustle autoloader, three crew', '尾舱自动装弹、三人乘员'],
    ],
  }),

  entry('ariete', {
    aliases: ['ariete', 'c1ariete', 'c1', '公羊', '阿里特'],
    nation: 'it',
    family: 'leopard',
    prefix: 'C1',
    name: 'C1 ARIETE',
    nameCn: 'C1「公羊」',
    designation: 'MBT · C1 ARIETE',
    mass: '54 t',
    crew: '4',
    powerpack: 'IVECO V-12 MTCA · 1300 hp',
    armament: 'OTO 120 mm L/44',
    armour: 'WELDED COMPOSITE, BOX TURRET',
    envelope: '9.52 × 3.42 × 2.50 m',
    barrelLength: 4.4,
    wheelCount: 7,
    features: { diesel: true, peri: true, wedge: false },
    structure: [
      ['Box welded turret, seven wheels', '方形焊接炮塔、七对负重轮'],
      ['OTO 120 mm L/44', 'OTO 120 毫米 L/44'],
      ['Italian composite side modules', '意大利复合侧装甲模块'],
    ],
  }),

  entry('arjun', {
    aliases: ['arjun', 'arjunmk1', 'arjunmk2', '阿琼', '阿诸那'],
    nation: 'in',
    family: 'challenger',
    prefix: 'ARJN',
    name: 'ARJUN Mk 1A',
    nameCn: '阿琼 Mk 1A',
    designation: 'MBT · ARJUN',
    mass: '68 t',
    crew: '4',
    powerpack: 'MTU 838 Ka-501 · 1400 hp',
    armament: '120 mm RIFLED',
    armour: 'KANCHAN COMPOSITE',
    envelope: '10.64 × 3.86 × 2.32 m',
    barrelLength: 5.4,
    wheelCount: 7,
    features: { diesel: true, thermalSleeve: true, hydrogas: true },
    structure: [
      ['Heavy Kanchan composite turret', '厚重「坎昌」复合炮塔'],
      ['120 mm rifled gun', '120 毫米线膛炮'],
      ['Seven wheels, hydro-pneumatic', '七对负重轮、油气悬挂'],
    ],
  }),

  entry('strv122', {
    aliases: ['strv122', 'strv-122', 'strv122b', '瑞典豹2'],
    nation: 'se',
    family: 'leopard',
    prefix: 'S122',
    name: 'STRV 122',
    nameCn: 'Strv 122',
    designation: 'MBT · LEOPARD 2 STRV 122',
    mass: '62 t',
    crew: '4',
    powerpack: 'MTU MB 873 Ka-501 · 1500 PS',
    armament: 'Rh-120 L/44',
    armour: 'LEOPARD 2A5 WEDGE + ROOF ARMOUR',
    envelope: '9.97 × 3.75 × 3.00 m',
    barrelLength: 4.4,
    wheelCount: 7,
    features: { diesel: true, wedge: true, peri: true },
    structure: [
      ['Leopard 2A5 wedge with extra roof armour', '豹 2A5 楔形装甲加厚车顶'],
      ['Swedish command-and-control suite', '瑞典火控与指挥套件'],
      ['Seven road wheels', '七对负重轮'],
    ],
  }),

  entry('t84', {
    aliases: ['t84', 't84u', 't84opyat', 'bmopilot', 'oplot', '堡垒', 't84堡垒'],
    nation: 'ua',
    family: 'soviet',
    prefix: 'T84',
    name: 'T-84 Oplot',
    nameCn: 'T-84「堡垒」',
    designation: 'MBT · T-84U OPLOT',
    mass: '51 t',
    crew: '3',
    powerpack: '6TD-2 DIESEL · 1200 hp',
    armament: 'KBA-3 125 mm + CAROUSEL',
    armour: 'NOZH ERA + BUSTLE APS',
    envelope: '9.72 × 3.77 × 2.28 m',
    barrelLength: 4.8,
    wheelCount: 6,
    features: { carousel: true, era: true, diesel: true, peri: true },
    structure: [
      ['T-80UD hull with Duplet ERA', 'T-80UD 车体与双层反应装甲'],
      ['Welded turret, panoramic sight', '焊接炮塔与全景瞄准镜'],
      ['Opposed-piston 6TD diesel', '对置活塞 6TD 柴油机'],
    ],
  }),

  entry('pt91', {
    aliases: ['pt91', 'pt91twardy', 'twardy', '坚固', 'pt91坚固'],
    nation: 'pl',
    family: 'soviet',
    prefix: 'PT91',
    name: 'PT-91 TWARDY',
    nameCn: 'PT-91「坚固」',
    designation: 'MBT · PT-91',
    mass: '45.5 t',
    crew: '3',
    powerpack: 'S-12U DIESEL · 850 hp',
    armament: '2A46 125 mm + CAROUSEL',
    armour: 'ERAWA REACTIVE BRICKS',
    envelope: '9.67 × 3.59 × 2.19 m',
    barrelLength: 4.8,
    wheelCount: 6,
    features: { carousel: true, era: true, diesel: true },
    structure: [
      ['T-72M1 with Polish Erawa ERA', 'T-72M1 加波兰 Erawa 反应装甲'],
      ['Carousel autoloader', '转盘自动装弹机'],
      ['Six road wheels', '六对负重轮'],
    ],
  }),

  entry('altay', {
    aliases: ['altay', 'altaymbt', '阿尔泰', '阿勒泰'],
    nation: 'tr',
    family: 'leopard',
    prefix: 'ALTY',
    name: 'ALTAY',
    nameCn: '阿尔泰',
    designation: 'MBT · ALTAY T3',
    mass: '65 t',
    crew: '4',
    powerpack: 'BATU DIESEL · 1500 hp',
    armament: '120 mm L/55',
    armour: 'MODULAR COMPOSITE + AKKOR APS',
    envelope: '10.30 × 3.90 × 2.60 m',
    barrelLength: 5.33,
    wheelCount: 7,
    features: { diesel: true, peri: true, wedge: true },
    structure: [
      ['K2 / Leopard-derived wedge turret', '源自 K2 / 豹 2 的楔形炮塔'],
      ['AKKOR APS launchers', 'AKKOR 主动防护'],
      ['Seven road wheels, L/55 gun', '七对负重轮与 L/55 火炮'],
    ],
  }),
];

function entry(id, spec) {
  return { id, ...spec };
}

export const CATALOG_BY_ID = new Map(CATALOG.map((t) => [t.id, t]));
