/**
 * Vehicle registry.
 *
 * Metadata only — geometry modules are imported on demand the first time a
 * vehicle is selected, so opening the atlas does not build seven tanks.
 *
 * `structure` and `texture` hold the design brief for each vehicle: the structural
 * descriptors are the identity features the geometry has to deliver, the texture
 * and environment descriptors are recorded for reference because a hidden-line
 * blueprint cannot render camouflage or weather.
 */
export const VEHICLES = [
  {
    id: 'm1a2',
    prefix: 'M1A2',
    flag: '🇺🇸',
    country: 'UNITED STATES',
    countryCn: '美国',
    name: 'M1A2 ABRAMS',
    nameCn: 'M1A2「艾布拉姆斯」',
    designation: 'MBT · SEPv3 · 1980 →',
    ink: 0xefcb9b,
    accent: 0xffa94d,
    sheet: '#12232c',
    specs: [
      ['CLASSIFICATION', 'MAIN BATTLE TANK · 66.8 t'],
      ['CREW', '4 · 车长 炮长 装填手 驾驶员'],
      ['POWERPACK', 'HONEYWELL AGT-1500 GAS TURBINE · 1500 hp'],
      ['ARMAMENT', '120 mm M256 SMOOTHBORE L/44'],
      ['ARMOUR', 'CHOBHAM + DU MESH · TUSK KIT'],
      ['ENVELOPE', '9.83 × 3.66 × 2.44 m'],
    ],
    structure: [
      ['Low-profile sleek chassis', '低矮流线型底盘'],
      ['Massive angular geometric turret', '巨大的几何棱角炮塔'],
      ['Long 120 mm smoothbore gun barrel', '修长的 120 毫米滑膛炮管'],
      ['Anti-RPG mesh screens', '防火箭弹铁丝网'],
    ],
    texture: [
      ['Desert tan camouflage', '荒漠黄迷彩'],
      ['Dust swirls', '沙尘漫天'],
      ['Matte steel armour texture', '哑光钢制装甲质感'],
    ],
    load: () => import('./vehicles/m1a2.js'),
  },
  {
    id: 'leopard2a7',
    prefix: 'LEO2',
    flag: '🇩🇪',
    country: 'GERMANY',
    countryCn: '德国',
    name: 'LEOPARD 2A7',
    nameCn: '豹 2A7',
    designation: 'MBT · KAMPFPANZER · 2014 →',
    ink: 0xb7d98e,
    accent: 0xe4ff6a,
    sheet: '#132518',
    specs: [
      ['CLASSIFICATION', 'MAIN BATTLE TANK · 67.5 t'],
      ['CREW', '4 · Kommandant Richtschütze Ladeschütze Fahrer'],
      ['POWERPACK', 'MTU MB 873 Ka-501 DIESEL · 1500 PS'],
      ['ARMAMENT', 'RHEINMETALL Rh-120 SMOOTHBORE L/55'],
      ['ARMOUR', 'WEDGE VORPANZER + AMAP SIDE MODULES'],
      ['ENVELOPE', '10.97 × 3.76 × 3.03 m'],
    ],
    structure: [
      ['Arrowhead shaped wedge-armour turret', '箭镞状楔形装甲炮塔'],
      ['Robust German military engineering', '粗犷的德国军工感'],
      ['Advanced panoramic commander sight', '先进的车长全景瞄准镜'],
    ],
    texture: [
      ['NATO three-colour woodland camouflage', '北约三色丛林迷彩'],
      ['Mud splashes on tracks', '履带上的泥浆飞溅'],
      ['Forest background with sunbeams', '阳光穿透的森林背景'],
    ],
    load: () => import('./vehicles/leopard2a7.js'),
  },
  {
    id: 'ztz99a',
    prefix: 'ZTZ99A',
    flag: '🇨🇳',
    country: 'CHINA',
    countryCn: '中国',
    name: 'ZTZ-99A',
    nameCn: '99A 式主战坦克',
    designation: 'MBT · TYPE 99A · 2011 →',
    ink: 0x9fe3c4,
    accent: 0xff6b6b,
    sheet: '#0c2420',
    specs: [
      ['CLASSIFICATION', 'MAIN BATTLE TANK · 58 t'],
      ['CREW', '3 · 车长 炮长 驾驶员（自动装弹）'],
      ['POWERPACK', '150HB DIESEL · 1500 hp'],
      ['ARMAMENT', '125 mm SMOOTHBORE + CAROUSEL AUTOLOADER'],
      ['ARMOUR', 'V-SHAPED MODULAR ERA + LASER DAZZLER'],
      ['ENVELOPE', '11.00 × 3.50 × 2.37 m'],
    ],
    structure: [
      ['V-shaped frontal modular reactive armour', 'V 型正面模块化反应装甲'],
      ['Roof-mounted laser countermeasure device', '车顶激光压制装置'],
      ['Sharp heavy armour plates', '锋利的重装甲板'],
    ],
    texture: [
      ['Digital grassland camouflage', '数码草地迷彩'],
      ['High-speed dashing across the plains', '平原高速驰骋'],
      ['Metallic grime', '金属油污质感'],
    ],
    load: () => import('./vehicles/ztz99a.js'),
  },
  {
    id: 't90m',
    prefix: 'T90M',
    flag: '🇷🇺',
    country: 'RUSSIA',
    countryCn: '俄罗斯',
    name: 'T-90M PRORYV',
    nameCn: 'T-90M「突破」',
    designation: 'MBT · OBJ. 188M · 2020 →',
    ink: 0xc3deff,
    accent: 0x86b8ff,
    sheet: '#111d2e',
    specs: [
      ['CLASSIFICATION', 'MAIN BATTLE TANK · 48 t'],
      ['CREW', '3 · командир наводчик механик-водитель'],
      ['POWERPACK', 'V-92S2F DIESEL · 1130 hp'],
      ['ARMAMENT', '2A46M-5 125 mm + CAROUSEL AUTOLOADER'],
      ['ARMOUR', 'RELIKT ERA + SLAT CAGE'],
      ['ENVELOPE', '9.53 × 3.78 × 2.23 m'],
    ],
    structure: [
      ['Low silhouette dome-shaped turret', '低矮穹顶状炮塔'],
      ['Fish-scale reactive armour bricks', '鱼鳞状反应装甲块'],
      ['Cage armour on turret rear', '炮塔后部的格栅装甲'],
    ],
    texture: [
      ['Shattered snow and winter camouflage', '破碎的雪地冬装迷彩'],
      ['Black exhaust smoke', '浓烈的黑色尾气'],
      ['Rugged mud-caked battlefield', '泥泞不堪的战场'],
    ],
    load: () => import('./vehicles/t90m.js'),
  },
  {
    id: 'challenger2',
    prefix: 'CR2',
    flag: '🇬🇧',
    country: 'UNITED KINGDOM',
    countryCn: '英国',
    name: 'CHALLENGER 2',
    nameCn: '挑战者 2',
    designation: 'MBT · FV4034 · 1998 →',
    ink: 0x8fd8ff,
    accent: 0xffc247,
    sheet: '#0d1f2e',
    specs: [
      ['CLASSIFICATION', 'MAIN BATTLE TANK · 62.5 t / 75 t TES'],
      ['CREW', '4 · commander gunner loader driver'],
      ['POWERPACK', 'PERKINS CV12-6A DIESEL · 1200 hp'],
      ['ARMAMENT', 'L30A1 120 mm RIFLED'],
      ['ARMOUR', 'DORCHESTER (CHOBHAM 2) + HEAVY SKIRTS'],
      ['ENVELOPE', '11.55 × 4.20 × 2.49 m'],
    ],
    structure: [
      ['Bulky and heavy-set silhouette', '笨重魁梧的轮廓'],
      ['Thick Chobham side skirts', '厚重的乔巴姆侧裙板'],
      ['Rifled gun barrel with thermal sleeve', '带有隔热套的线膛炮管'],
    ],
    texture: [
      ['Monolithic steel fortress look', '整体式钢铁堡垒外观'],
      ['Rain-drenched dark green paint', '雨水浸湿的深绿涂装'],
      ['Grim cinematic fog', '冷峻的电影感迷雾'],
    ],
    load: () => import('./vehicles/challenger2.js'),
  },
  {
    id: 'leclerc',
    prefix: 'LEC',
    flag: '🇫🇷',
    country: 'FRANCE',
    countryCn: '法国',
    name: 'LECLERC XLR',
    nameCn: '勒克莱尔',
    designation: 'MBT · EPC · 1992 →',
    ink: 0xcbbbff,
    accent: 0xa78bfa,
    sheet: '#161c33',
    specs: [
      ['CLASSIFICATION', 'MAIN BATTLE TANK · 56.5 t'],
      ['CREW', '3 · chef gunner pilote（自动装弹）'],
      ['POWERPACK', 'SACM V8X-1500 HYPERBAR · 1500 hp'],
      ['ARMAMENT', 'GIAT CN120-26 L/52 + BUSTLE AUTOLOADER'],
      ['ARMOUR', 'MODULAR COMPOSITE PANELS'],
      ['ENVELOPE', '9.87 × 3.71 × 2.53 m'],
    ],
    structure: [
      ['Ultra-compact high-tech turret', '超紧凑高科技炮塔'],
      ['Smooth modular armour panels', '光滑的模块化装甲板'],
      ['Clean futuristic military design', '整洁的未来主义军工设计'],
    ],
    texture: [
      ['Satin finish green and brown paint', '半哑光绿褐涂装'],
      ['Bright daytime lighting', '明亮的白昼光影'],
      ['High-mobility dust trails', '高速机动留下的尘土轨迹'],
    ],
    load: () => import('./vehicles/leclerc.js'),
  },
  {
    id: 'tiger1',
    prefix: 'TGR',
    flag: '🇩🇪',
    country: 'GERMANY · 1943',
    countryCn: '德国（二战）',
    name: 'TIGER I',
    nameCn: '虎 I',
    designation: 'HEAVY TANK · PZ.KPFW. VI AUSF. E',
    ink: 0xa8c6d8,
    accent: 0xffc247,
    sheet: '#111c26',
    specs: [
      ['CLASSIFICATION', 'HEAVY TANK · 57 t'],
      ['CREW', '5 · 车长 炮手 装填手 驾驶员 无线电员'],
      ['POWERPACK', 'MAYBACH HL 230 P45 · 700 PS'],
      ['ARMAMENT', '8.8 cm KwK 36 L/56'],
      ['ARMOUR', '100 / 80 / 82 mm ROLLED PLATE'],
      ['ENVELOPE', '8.45 × 3.71 × 3.00 m'],
    ],
    structure: [
      ['Interleaved Schachtellaufwerk road wheels', '交错式负重轮'],
      ['Sponsons overhanging both tracks', '悬垂于履带之上的侧裙'],
      ['Stepped nose and vertical driver plate', '阶梯式车头与垂直驾驶员装甲板'],
    ],
    texture: [
      ['Dunkelgelb base with Zimmerit', '暗黄底漆与防磁涂层'],
      ['Eastern front mud', '东线泥泞'],
      ['Rolled homogeneous steel', '轧制均质钢板质感'],
    ],
    load: () => import('./vehicles/tiger1.js'),
  },
];

export const VEHICLE_BY_ID = new Map(VEHICLES.map((v) => [v.id, v]));
